# state.py

from typing_extensions import TypedDict


class EssayState(TypedDict):
    """
    Shared state used by the LangGraph workflow.
    """

    # Original or updated essay
    essay: str

    # Feedback generated by the reviewer
    feedback: str

    # Essay after improvement
    improved_essay: str

    # Decision returned by reviewer
    # Values: improve | finish
    decision: str

    # Number of review cycles completed
    iteration: int